# CORRIGINDO TEXTOS

Inicial: "   Jean  DaNIEL  Borges    Gamboa   "<br>
Final: "JEAN DANIEL BORGES GAMBOA"



```
# Isto está formatado como código
Inicial: "   Jean  DaNIEL  Borges    Gamboa   "<br>
Final: "JEAN DANIEL BORGES GAMBOA"
```

In [ ]:
nome = "   Jean  DaNIEL  Borges    Gamboa   "
print(nome)

   Jean  DaNIEL  Borges    Gamboa

In [ ]:
resultado = nome.strip().upper().replace("  "," ")
print(resultado)

#primeiro replace não corrige os 3 espaços. usar novamente
resultado = resultado.strip().upper().replace("  "," ")
print(resultado)

JEAN DANIEL BORGES  GAMBOA
JEAN DANIEL BORGES GAMBOA

In [ ]:
nome = input("Entre com o nome de usuário: ")
idade = input("Entre com sua idade: ")
print("Seu nome é " + nome)
print("Sua idade é " + idade)

Entre com o nome de usuário: Jean Gamboa
Entre com sua idade: 1212
Seu nome é Jean Gamboa
Sua idade é 1212

In [ ]:
tipo_nome = type(nome)
tipo_idade = type(idade)

print(tipo_nome)
print(tipo_idade)
print(str(tipo_nome) + " " + str(tipo_idade))

<class 'str'>
<class 'int'>
<class 'str'> <class 'int'>

In [ ]:
# transformar idade em inteiro em vez de str
idade = int(idade)
tipo_idade = type(idade)
print(tipo_idade)

<class 'int'>

In [ ]:
print("A pessoa se chama "+ nome + " e tem " + str(idade) + " anos de idade")
print(f"A pessoa se chama {nome} e tem {idade} anos de idade")

A pessoa se chama Jean Gamboa e tem 1212 anos de idade
A pessoa se chama Jean Gamboa e tem 1212 anos de idade

# **Estruturas Condicionais**

## Fulano pode ou não entrar na festa

In [ ]:
nome = input("Entre com o nome de usuário: ")
idade = int(input("Entre com sua idade: "))
print("Seu nome é " + nome)
print(f"Sua idade é {idade}")

Entre com o nome de usuário: Jean Gamboa
Entre com sua idade: 18
Seu nome é Jean Gamboa
Sua idade é 18

In [ ]:
if idade >= 18:
  print(f"{nome} pode entrar na festa porque é maior de idade (tem {idade} anos).")
else:
  print(f"{nome} não pode entrar na festa porque é menor de idade (tem {idade} anos).")

Jean Gamboa pode entrar na festa porque é maior de idade (tem 18 anos).

## Minhas notas na escola

In [ ]:
media = float(input("Digite a sua Media na escola: "))

if media >= 7.0:
  print("Aprovado")
elif media >= 5.0:
  print("Recuperação")
else:
  print("Reprovado")

Digite a sua Media na escola: 123
Aprovado

In [ ]:
media = float(input("Digite a sua Media na escola: "))

if media < 5.0:
  print("Reprovado")
elif media < 7.0:
  print("Recuperação")
else:
  print("Aprovado")

Digite a sua Media na escola: 134
Aprovado

# Estruturas de Repetição - While

In [ ]:
#print("**********") imprime 10 asteriscos
# queremos imprimir 500 asteriscos. como fazer? Usar While

n = 1

while n <= 10 :
  print(bool(n))
  n = n + 1

True
True
True
True
True
True
True
True
True
True

# **IMPORTANDO A IA DO GOOGLE**

In [ ]:
import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('chave_teste')

In [ ]:
from google import genai

client = genai.Client()

In [ ]:
chat = 1

In [ ]:
# client.models.generate_content(model="gemini-2.5-flash", contents="quais os modelos de IA disponíveis pelo google?")
# não consegui saber quais são os "models" que eu posso usar, porque o site que ele mostrou era diferente.

resposta = client.models.generate_content(model="gemini-2.5-flash", contents="quando nasceu napoleão ?")
print(resposta.text)

Napoleão Bonaparte nasceu em **15 de agosto de 1769**.

In [ ]:
chat = client.chats.create(model="gemini-2.5-flash")
resposta = chat.send_message("me diga em que ano nasceu Da Vinci?")
print(resposta.text)

Leonardo da Vinci nasceu em **1452**.

In [ ]:
resposta2 = chat.send_message("e agora em que ano nasceu napoleão?")
print(resposta2.text)

Napoleão Bonaparte nasceu em **1769**.

In [ ]:
chat.get_history()

[UserContent(
   parts=[
     Part(
       text='me diga em que ano nasceu Da Vinci?'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text='Leonardo da Vinci nasceu em **1452**.'
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='responda sim ou não'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text='Sim.'
     ),
   ],
   role='model'
 ),
 UserContent(
   parts=[
     Part(
       text='de novo'
     ),
   ],
   role='user'
 ),
 Content(
   parts=[
     Part(
       text='Sim.'
     ),
   ],
   role='model'
 )]

In [ ]:
prompt = input("Digite a sua pergunta: ")

while prompt != "fim":
  resposta = chat.send_message(prompt)
  print(resposta.text + "\n")
  prompt = input("Digite a sua pergunta: ")

Digite a sua pergunta: responda sim ou não
Sim.

Digite a sua pergunta: de novo
Sim.

Digite a sua pergunta: fim

In [ ]:
prompt.get_history()

AttributeError: 'str' object has no attribute 'get_history'

# **Estruturas de Dados**

## Listas

In [ ]:
lista_de_nomes = ["João Silva", "Maria Santos", "José Oliveira", "Ana Souza", "Antônio Pereira"]
# elementos:            0              1               2              3                4
print(lista_de_nomes[3])

Ana Souza

In [ ]:
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

print(lista_de_medias[3])

1.4

In [ ]:
n = 0
print(lista_de_medias)
while n <= 4 :

  lista_de_medias[n] = lista_de_medias[n] + 1
  if lista_de_medias[n] > 10 :
    lista_de_medias[n] = 10
  n = n +1

  print(lista_de_medias)

[8.9, 7.5, 4.2, 1.4, 9.5]
[9.9, 7.5, 4.2, 1.4, 9.5]
[9.9, 8.5, 4.2, 1.4, 9.5]
[9.9, 8.5, 5.2, 1.4, 9.5]
[9.9, 8.5, 5.2, 2.4, 9.5]
[9.9, 8.5, 5.2, 2.4, 10]

In [ ]:
# len(lista_de_medias) mostra o cumprimento da lista
cumprimento_medias = len(lista_de_medias)
print(cumprimento_medias) # 5 elementos

print("\n")

# último elemento da lista, dá pra usar números negativos
print(lista_de_medias[-1]) # último elemento
print(lista_de_medias[-2]) # penúltimo elemento ... e assim por diante

5


10
2.4

In [ ]:
# particionando a lista

print(lista_de_nomes)

print("\n")

print(lista_de_nomes[1:3]) #pega do elemento do primeiro número até o elemento do segundo número, não incluído. Portanto, vai apresentar só o elemento 1 e 2, o 3 não inclui
print(lista_de_nomes[1:4]) #agora sim inclui o 3o elemento

print("\n")

print(lista_de_nomes[1:]) #pega do elemento 1 até o final
print(lista_de_nomes[:4]) #pega do começo até o elemento 4

['João Silva', 'Maria Santos', 'José Oliveira', 'Ana Souza', 'Antônio Pereira']


['Maria Santos', 'José Oliveira']
['Maria Santos', 'José Oliveira', 'Ana Souza']


['Maria Santos', 'José Oliveira', 'Ana Souza', 'Antônio Pereira']
['João Silva', 'Maria Santos', 'José Oliveira', 'Ana Souza']

In [ ]:
lista_de_nomes = ["João Silva", "Maria Santos", "José Oliveira", "Ana Souza", "Antônio Pereira"]
# elementos:            0              1               2              3                4
print(lista_de_nomes[3])

Ana Souza

In [ ]:
#incluir elementos

lista_de_nomes.append("Jean Gamboa")
print(lista_de_nomes)

#append só permite entrada de um elemento

['João Silva', 'Maria Santos', 'José Oliveira', 'Ana Souza', 'Antônio Pereira', 'Jean Gamboa']

In [ ]:
lista_de_nomes.append("Ana Gamboa", "Bento Gamboa")
print(lista_de_nomes)

#dá erro, pq append só inclui um elemento por vez. Se incluir dois elementos como lista, ele inclui a lista como um elemento

TypeError: list.append() takes exactly one argument (2 given)

In [ ]:
lista_de_nomes.append(["Ana Gamboa", "Bento Gamboa"])
print(lista_de_nomes)

#último elemento entrou com duas pessoas agora.

In [ ]:
print(lista_de_nomes[5])

#dá pra encavalar colchetes se quiser pegar um elemento específico de uma lista dentro de outra lista
print(lista_de_nomes[5][0])

In [ ]:
#se quiser incluir uma série de elementos numa lista, dá pra usar o método extend

lista_de_nomes.extend(["Daniel Schmitz", "Edson Mastelini", "Lourdes Borges"]) #informa uma lista e ele inclui no final como que 'concatenado'
print(lista_de_nomes)

In [ ]:
#se quiser remover um elemento, pode usar o método remove ou pop
#remove preciso informar o valor do elemento; pop posso informar a posição do elemento na lista
#no POP, se não informar nada, ele exclui o último elemento

lista_de_nomes.remove("Ana Souza")
print(lista_de_nomes)

In [ ]:
lista_de_nomes.pop()   #exclui o último elemento da lista
print(lista_de_nomes)

In [ ]:
lista_de_nomes.pop(4) #exclui o elemento na posição 4 (começando do elemento zero)
print(lista_de_nomes)

## Dicionários

In [ ]:
lista_de_nomes = ["João Silva", "Maria Santos", "José Oliveira", "Ana Souza", "Antônio Pereira"]
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

# nas variáveis acima, nada obriga que, por exemplo, o elemento 1 da primeira lista (Maria Santos) seja o dono da média do elemento 1 da segunda lista (7.5)
# se eu incluir ou excluir um elemento na lista, as notas vão ficar desordenadas. Pra isso servem os "dicionários"
# dicionários são sequências de dados ordenados de dois em dois, onde o primeiro valor é a 'chave' e o segundo valor é o 'valor correspondente à chave'

dict_nomes_e_medias1 = {
    "João Silva":8.9,
    "Maria Santos":7.5,
    "José Oliveira":4.2,
    "Ana Souza":1.4,
    "Antônio Pereira":9.5
}

print(dict_nomes_e_medias1)

{'João Silva': 8.9, 'Maria Santos': 7.5, 'José Oliveira': 4.2, 'Ana Souza': 1.4, 'Antônio Pereira': 9.5}

In [ ]:
# alternativamente, sabendo as variáveis acima, dá pra chamar as variáveis

dict_nomes_e_medias2 = {
    lista_de_nomes[0]:lista_de_medias[0],
    lista_de_nomes[1]:lista_de_medias[1],
    lista_de_nomes[2]:lista_de_medias[2],
    lista_de_nomes[3]:lista_de_medias[3],
    lista_de_nomes[4]:lista_de_medias[4],
}

print(dict_nomes_e_medias1)

{'João Silva': 8.9, 'Maria Santos': 7.5, 'José Oliveira': 4.2, 'Ana Souza': 1.4, 'Antônio Pereira': 9.5}

In [ ]:
# ainda alternativamente, se a lista for imensamente grande, dá pra fazer um while ? dá!

n = 0
while n < 5 :
  dict_nomes_e_medias3 = {
      lista_de_nomes[n]:lista_de_medias[n]
  }
  n = n + 1

print(dict_nomes_e_medias1)

{'João Silva': 8.9, 'Maria Santos': 7.5, 'José Oliveira': 4.2, 'Ana Souza': 1.4, 'Antônio Pereira': 9.5}

In [ ]:
dict_nomes_e_medias1["João Silva"]

8.9

In [ ]:
#ou
dict_nomes_e_medias1.get("João Silva")

8.9

In [ ]:
dict_nomes_e_medias1.pop("Antônio Pereira")

#exige um argumento - retorna o valor do argumento na lista e exclui esse elemento da lista

9.5

In [ ]:
print(dict_nomes_e_medias1)

{'João Silva': 8.9, 'Maria Santos': 7.5, 'José Oliveira': 4.2, 'Ana Souza': 1.4}

In [ ]:
dict_nomes_e_medias1.items()

dict_items([('João Silva', 8.9), ('Maria Santos', 7.5), ('José Oliveira', 4.2), ('Ana Souza', 1.4)])

In [ ]:
dict_nomes_e_medias1.keys()

dict_keys(['João Silva', 'Maria Santos', 'José Oliveira', 'Ana Souza'])

In [ ]:
dict_nomes_e_medias1.values()

dict_values([8.9, 7.5, 4.2, 1.4])

### Desafio - não deu pra entender direito. Ele enunciou melhor no começo da resolução.

- Usar dicionários de forma que as chaves sem 'nome' e 'média', e os valores sejam os nomes e as médias dos alunos

In [ ]:
# nada a ver. Agora vendo a resolução saquei

dict_desafio = [
    {"nome":"João Silva", "media":8.9},
    {"nome":"Maria Santos", "media":7.5},
    {"nome":"José Oliveira", "media":4.2},
    {"nome":"Ana Souza", "media":1.4},
    {"nome":"Antônio Pereira", "media":9.5}
]

dict_desafio[0]

{'nome': 'João Silva', 'media': 8.9}

In [ ]:
dict_desafio[0]["media"]

8.9

#Loop "For"

In [ ]:
dict_desafio = [
    {"nome":"João Silva", "media":8.9},
    {"nome":"Maria Santos", "media":7.5},
    {"nome":"José Oliveira", "media":4.2},
    {"nome":"Ana Souza", "media":1.4},
    {"nome":"Antônio Pereira", "media":9.5}
]

In [ ]:
n = 0

while n < len(dict_desafio):
  print(dict_desafio[n])
  n = n + 1

{'nome': 'João Silva', 'media': 8.9}
{'nome': 'Maria Santos', 'media': 7.5}
{'nome': 'José Oliveira', 'media': 4.2}
{'nome': 'Ana Souza', 'media': 1.4}
{'nome': 'Antônio Pereira', 'media': 9.5}

In [ ]:
for n in dict_desafio:
  print(n)

  # percorre cada um dos elementos, de n=0 a n=4

{'nome': 'João Silva', 'media': 8.9}
{'nome': 'Maria Santos', 'media': 7.5}
{'nome': 'José Oliveira', 'media': 4.2}
{'nome': 'Ana Souza', 'media': 1.4}
{'nome': 'Antônio Pereira', 'media': 9.5}

In [ ]:
# então ok. O que eu tinha antes era:

lista_de_nomes = ["João Silva", "Maria Santos", "José Oliveira", "Ana Souza", "Antônio Pereira"]
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

# para formar o dict_desafio eu preciso:

n = 0
dict_desafio = [] # inicializar a lista vazia

while n < len(lista_de_nomes):
  dict_interno = {"nome":lista_de_nomes[n], "media":lista_de_medias[n] }
  dict_desafio.append(dict_interno)
  n = n + 1

print(dict_desafio)

[{'nome': 'João Silva', 'media': 8.9}, {'nome': 'Maria Santos', 'media': 7.5}, {'nome': 'José Oliveira', 'media': 4.2}, {'nome': 'Ana Souza', 'media': 1.4}, {'nome': 'Antônio Pereira', 'media': 9.5}]

In [ ]:
# alternativamente:

lista_de_nomes = ["João Silva", "Maria Santos", "José Oliveira", "Ana Souza", "Antônio Pereira"]
lista_de_medias = [8.9, 7.5, 4.2, 1.4, 9.5]

n = 0
dict_desafio = [] # inicializar a lista vazia

while n < len(lista_de_nomes):  # não preciso criar uma variável pro dicionário interno, basta informar dentro do append
  dict_desafio.append({"nome":lista_de_nomes[n], "media":lista_de_medias[n] })
  n  += 1

print(dict_desafio)

[{'nome': 'João Silva', 'media': 8.9}, {'nome': 'Maria Santos', 'media': 7.5}, {'nome': 'José Oliveira', 'media': 4.2}, {'nome': 'Ana Souza', 'media': 1.4}, {'nome': 'Antônio Pereira', 'media': 9.5}]

In [ ]:
# agora usando o loop 'for'. Inicialmente, imprimir a lista:

for element in dict_desafio:
  print(element)

{'nome': 'João Silva', 'media': 8.9}
{'nome': 'Maria Santos', 'media': 7.5}
{'nome': 'José Oliveira', 'media': 4.2}
{'nome': 'Ana Souza', 'media': 1.4}
{'nome': 'Antônio Pereira', 'media': 9.5}

In [ ]:
for n in range(0,15,3):
  print(n)


# no range:
# se tiver 1 número, é o range mesmo;
# se tiver 2 números, é do 1º ao 2º número;
# se tiver 3 números, é do 1º ao 2º número, seguindo em espaços do 3º número.

0
3
6
9
12

In [ ]:
pessoa = {
    "nome": "Fabricio",
    "idade": 19,
    "altura": 1.83
}

print(pessoa)

for chave, valor in pessoa.items():
  print(f"A chave é {chave}, o valor é {valor}")

  # items pega chave e valor;
  # atributo keys pega só as chaves, atributo values pega só os valores

{'nome': 'Fabricio', 'idade': 19, 'altura': 1.83}
A chave é nome, o valor é Fabricio
A chave é idade, o valor é 19
A chave é altura, o valor é 1.83

In [ ]:
#Se eu declarar só uma variável no items, ele corre todas as chaves e valores, mas como um elemento só

for chave in pessoa.items():
  print(f"A chave é {chave}, e o valor é {chave}")

A chave é ('nome', 'Fabricio'), e o valor é ('nome', 'Fabricio')
A chave é ('idade', 19), e o valor é ('idade', 19)
A chave é ('altura', 1.83), e o valor é ('altura', 1.83)

In [ ]:
for n in range(11):
  if n % 2 == 0:
    print(n)

0
2
4
6
8
10

# Funções

In [ ]:
texto1 = "   Fabrício CARRaro  da alura   "
texto2 = "  mAriAna   siLvA   saNToS   "
texto3 = "   PEdrO  AlvEs de    oLIVEIRA  "
texto4 = "  aNa  CARolinA   souzA   "
texto5 = "   rafaEL   GonCALVES   costa   "
texto6 = "  LuIZA   FERreira  pereira  "

In [ ]:
def escreve_texto_corretamente(texto):
  texto = texto.strip().upper().replace("  "," ")
  print(texto)

In [ ]:
escreve_texto_corretamente(texto3)

print(texto3)

#não tira mais do que 2 espaços. Pra isso, precisamos de outros métodos
#até daria pra fazer com um while, mas enfim

PEDRO ALVES DE  OLIVEIRA
   PEdrO  AlvEs de    oLIVEIRA

In [ ]:
print(texto1.split())

len(texto1.split())

['Fabrício', 'CARRaro', 'da', 'alura']

4

In [ ]:
def corrige_texto(texto):
  texto_novo = texto.upper()
  lista_de_palavras = texto_novo.split()
  nome_final = " ".join(lista_de_palavras)
  return nome_final

  # métodos split e join

In [ ]:
corrige_texto(texto3)

'PEDRO ALVES DE OLIVEIRA'

In [ ]:
#Criar uma função mais simplificada da função anterior

def corrige_texto2(texto):
  return " ".join(texto.upper().split())

In [ ]:
corrige_texto2(texto3)

'PEDRO ALVES DE OLIVEIRA'

In [ ]:
salas_de_aula = ["Sala 1", "Sala 2", "Sala 3"]

import random

def aloca_alunos(aluno, classe):
  sala = random.choice(classe)

  dict_aluno = {
      "nome": aluno,
      "sala": sala
  }
  print(dict_aluno)

In [ ]:
nome_corrigido = corrige_texto(texto1)

aloca_alunos(nome_corrigido, salas_de_aula)

{'nome': 'FABRÍCIO CARRARO DA ALURA', 'sala': 'Sala 1'}

In [ ]:
### Desafio:

### 1.Pedir pra uma IA gerar em Python uma lista de 20 emails pra você.
### 2.Criar uma função que vai receber como argumento/parâmetro uma lista de e-mails, percorrer essa lista de e-mails,
###   e, para cada e-mail da lista, ela irá chamar a IA do GEMINI via API e pedir pra ela resumir pra você todos os
###   e-mails em apenas uma linha, definindo o que essa pessoa queria no e-mail

In [ ]:
# @title
# ETAPA 1

# Lista de 20 textos de e-mail com temas variados em Python

lista_emails = [
    # 1. Confirmação de Reunião (Trabalho)
    """
    Assunto: Confirmação de Reunião: Alinhamento de Projeto

    Prezados,

    Este e-mail é para confirmar nossa reunião de alinhamento sobre o Projeto Alfa para amanhã, 17/11, às 10:00.

    A pauta será a revisão do cronograma e a definição das próximas entregas.

    O link do Google Meet é: [link_da_reuniao]

    Atenciosamente,
    Gerência de Projetos
    """,

    # 2. Resposta Automática (Fora do Escritório)
    """
    Assunto: Resposta Automática: Férias

    Olá,

    Obrigado pelo seu e-mail. Estarei fora do escritório em período de férias de 16/11 a 30/11, com retorno previsto para 01/12.

    Terei acesso limitado aos meus e-mails. Para assuntos urgentes, por favor, contate [Nome do Colega] em [email_colega@empresa.com].

    Atenciosamente,
    [Seu Nome]
    """,

    # 3. Pedido de Atualização (Trabalho)
    """
    Assunto: ATUALIZAÇÃO: Status do Relatório Semanal

    Olá, Equipe,

    Por favor, poderiam me enviar uma breve atualização sobre o status do relatório semanal?

    Preciso consolidar os dados até o final da tarde de hoje (16/11) para a apresentação de amanhã.

    Obrigado,
    [Seu Nome]
    """,

    # 4. Marketing (Promoção)
    """
    Assunto: SÓ HOJE: 40% OFF em todo o site!

    Olá [Nome do Cliente],

    Você não vai querer perder essa! Somente pelas próximas 24 horas, use o cupom QUARENTAOFF e ganhe 40% de desconto em qualquer produto da nossa loja.

    Corra para o nosso site e aproveite antes que acabe!

    [Link para o Site]

    Equipe de Vendas
    """,

    # 5. Transacional (Confirmação de Pedido)
    """
    Assunto: Pedido #87652 Confirmado!

    Olá, Maria,

    Obrigado por comprar conosco! Seu pedido #87652 foi recebido e está sendo processado.

    Resumo do Pedido:
    - 1x Fone de Ouvido Bluetooth (Preto)
    - Total: R$ 149,90

    Você receberá um novo e-mail assim que seu pedido for enviado.

    Atenciosamente,
    Loja XYZ
    """
]

# Você pode imprimir um dos e-mails para testar:
# print(lista_emails[0])

In [ ]:
import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('chave_teste')

from google import genai
client = genai.Client()

def resumir_email(lista):
  for i, email in enumerate(lista):
    resumo = client.models.generate_content(
        model="gemini-2.5-flash",
        contents= f"resuma em apenas uma linha o seguinte e-mail: {email}"
        )

    print(f"{i+1}. {resumo.text}")
    print("-" * 50)

In [ ]:
resumir_email(lista_emails)

1. Confirmação da reunião do Projeto Alfa para amanhã, 17/11, às 10h, via Google Meet, para revisão de cronograma e definição de entregas.
--------------------------------------------------
2. Estarei de férias de 16/11 a 30/11 com acesso limitado; para urgências, contate [Nome do Colega].
--------------------------------------------------
3. Solicitação urgente de atualização sobre o relatório semanal para consolidação hoje, visando a apresentação de amanhã.
--------------------------------------------------
4. Aproveite 40% de desconto em todo o site por 24h usando o cupom QUARENTAOFF.
--------------------------------------------------
5. Maria, seu pedido #87652 (Fone de Ouvido Bluetooth) foi confirmado e está sendo processado.
--------------------------------------------------

In [ ]:
# alternativamente ao "enumerate", quero testar se o for funciona de outro jeito:


def resumir_email(lista):
  i = 1
  for email in lista:
    resumo = client.models.generate_content(
        model="gemini-2.5-flash",
        contents= f"resuma em apenas uma linha o seguinte e-mail: {email}"
        )

    print(f"{i}. {resumo.text}")
    print("-" * 50)
    i += 1

In [ ]:
!pip install groq

Collecting groq
  Downloading groq-0.36.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: anyio<5,>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from groq) (4.11.0)
Requirement already satisfied: distro<2,>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from groq) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from groq) (0.28.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from groq) (2.11.10)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from groq) (1.3.1)
Requirement already satisfied: typing-extensions<5,>=4.10 in /usr/local/lib/python3.12/dist-packages (from groq) (4.15.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5,>=3.5.0->groq) (3.11)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (2025.11.12)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->groq) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->groq) (0.16.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=1.9.0->groq) (0.4.2)
Downloading groq-0.36.0-py3-none-any.whl (137 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 137.3/137.3 kB 4.8 MB/s eta 0:00:00
Installing collected packages: groq
Successfully installed groq-0.36.0

In [ ]:
import os
from google.colab import userdata
os.environ["GROQ_API_KEY"] = userdata.get('groq_key1')

from groq import Groq

client = Groq()
completion = client.chat.completions.create(
    model="openai/gpt-oss-20b",
    messages=[
      {
        "role": "user",
        "content": "de que é feito o Sol? responda sucintamente"
      }

    ],
    temperature=2,
    max_completion_tokens=8192,
    top_p=1,
    reasoning_effort="medium",
    stream=True,
    stop=None
)

for chunk in completion:
    print(chunk.choices[0].delta.content or "", end="")

O Sol é predominantemente composto de **hidrogênio (≈ 74 % da massa)** e **elétron**; cerca de **24 % em **hélio** e poucos porcentos de elementos mais pesados como carbono, oxigênio, ferro, neon e silício. Estes “metais” compõem, em soma, menos de 2 % da massa total.

# Lendo e escrevendo em arquivos usando Python

In [ ]:
import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('chave_teste')

from google import genai
client = genai.Client()

def resumir_email(lista):
  lista_de_resumos = []

  for i, email in enumerate(lista):
    resumo = client.models.generate_content(
        model="gemini-2.5-flash",
        contents= f"resuma em apenas uma linha o seguinte e-mail: {email}"
        )
    resposta = f"{i+1}. {resumo.text}"
    print(resposta)
    print("-" * 50)

    lista_de_resumos.append(resposta + "\n")
  return lista_de_resumos

In [ ]:
#trouxe pra cá a execução da função pra facilitar rodar de novo

lista_para_documento = resumir_email(lista_emails)

1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.
--------------------------------------------------
2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.
--------------------------------------------------
3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.
--------------------------------------------------
4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.
--------------------------------------------------
5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.
--------------------------------------------------

In [ ]:
with open("lista-de-resumos.txt", "w", encoding="utf-8") as documento:
  documento.writelines(lista_para_documento)

# deu certo assim, porque ao contrário do ensinado na aula eu botei um +"\n" no
# final de cada resposta, no append dentro da função.
# De igual modo, posso usar um for e 'write' com "\n" por fora e funciona tbm.
# Vou fazer assim pra testar ficar com uma linha de espaço entre cada texto

In [ ]:
with open("lista-de-resumos.txt", "a", encoding="utf-8") as documento:
  for i in lista_para_documento:
    documento.write(i + "\n")

#usei o modo "a" e incluiu a lista de novo. Deu tudo certo :)

In [ ]:
nova_lista_de_leitura = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as documento:
  for linha in documento:
    nova_lista_de_leitura.append(linha) #linha é o 'i', o contador

In [ ]:
nova_lista_de_leitura

#leu tudo, só que ficou com todos os \n. Inclusive slots apenas com \n das linhas em branco

['1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.\n',
 '2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.\n',
 '3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.\n',
 '4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.\n',
 '5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.\n',
 '1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.\n',
 '\n',
 '2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.\n',
 '\n',
 '3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.\n',
 '\n',
 '4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.\n',
 '\n',
 '5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.\n',
 '\n']

In [ ]:
conteudo = ""

with open("lista-de-resumos.txt", "r", encoding="utf-8") as documento:
  conteudo = documento.read()

In [ ]:
conteudo

#pior ainda, com o método read salvou tudo numa linha só.

'1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.\n2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.\n3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.\n4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.\n5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.\n1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.\n\n2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.\n\n3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.\n\n4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.\n\n5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.\n\n'

In [ ]:
doc_lido = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as documento:
  for linha in documento:
    doc_lido.append(linha.strip()) #linha é o 'i', o contador

In [ ]:
doc_lido

# limpa todas as quebras de linha, mas as células 6, 8, 10, 12 e 14 ficaram vazias (sem o \n)

['1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.',
 '2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.',
 '3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.',
 '4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.',
 '5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.',
 '1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.',
 '',
 '2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.',
 '',
 '3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.',
 '',
 '4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.',
 '',
 '5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.',
 '']

In [ ]:
doc_lido2 = []

with open("lista-de-resumos.txt", "r", encoding="utf-8") as documento:
  doc_lido2 = documento.readlines()

In [ ]:
doc_lido2

#ficou o 'nova_lista_de_leitura.

['1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.\n',
 '2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.\n',
 '3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.\n',
 '4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.\n',
 '5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.\n',
 '1. Reunião do Projeto Alfa confirmada para amanhã, 17/11, às 10h, via Google Meet, com pauta de revisão de cronograma e definição de entregas.\n',
 '\n',
 '2. O remetente está de férias de 16/11 a 30/11 (retorno 01/12) com acesso limitado e pede para contatar [Nome do Colega] para assuntos urgentes.\n',
 '\n',
 '3. Solicito a atualização do relatório semanal hoje para consolidar os dados visando a apresentação de amanhã.\n',
 '\n',
 '4. Desconto de 40% em todo o site por 24 horas usando o cupom QUARENTAOFF.\n',
 '\n',
 '5. Confirmação do pedido #87652 de Maria (fone Bluetooth), já em processamento pela Loja XYZ.\n',
 '\n']

# Pandas

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("/content/meu_csv.csv")

FileNotFoundError: [Errno 2] No such file or directory: '/content/meu_csv.csv'

In [ ]:
df.head()

In [ ]:
df.tail(10)

Desafio:
1. Criar um arquivo .txt a partir de uma lista de perguntas vindas de uma lista em Python.
2. Ler essas perguntas desse arquivo .txt. e salvá-las em uma lista Python.
3. Obter respostas de um LLM para cada uma.
4. Salvar os resultados em um novo arquivo .csv.
5. Ler o arquivo .csv usando Pandas.

In [ ]:
# Etapa 1:
lista_de_perguntas = [
    "Qual é a capital da França?",
    "Quem pintou a Mona Lisa?",
    "Quanto é 2 + 2?",
    "Quem inventou o Telefone?",
    "Qual é o maior planeta do Sistema Solar",
    "Quando nasceu Napoleão?",
]

In [ ]:
with open("exercicio.txt", "w") as arquivo:
  for i in lista_de_perguntas:
    arquivo.write(i + "\n")

# de propósito, não botei o encoding e funcionou igual. Aparentemente funciona, mas pode dar problema em algum contexto. Bom saber

In [ ]:
# Etapa 2:
lista_lida1 = []

with open("exercicio.txt", "r") as arquivo:
  lista_lida1 = arquivo.readlines()

#desta forma, com readlines não consigo usar strip. Vou fazer de novo com for.

In [ ]:
lista_lida1 # COM READLINES()

In [ ]:
lista_lida2 = []

with open("exercicio.txt", "r") as arquivo:
  for i in arquivo:
    lista_lida2.append(i.strip())

In [ ]:
lista_lida2 # COM FOR E STRIP()

In [ ]:
# Etapa 3:

import os # não basta apenas usar o código disponível na chavinha, tem que
          # importar o os e salvar o "usardata.get" numa variável de ambiente
          # chamada "GOOGLE_API_KEY"
          #
          # IMPORTANTE NOTAR que na vez que chamamos o GROQ usamos a
          # GROQ_API_KEY

from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get("chave_teste")

from google import genai
minha_IA = genai.Client()

# função que dá uma resposta para cada pergunta e coloca numa lista
def responder_perguntas(pergunta):
  lista_de_respostas = []

  for i, pergunta in enumerate(pergunta):
    resposta = minha_IA.models.generate_content(
        model="gemini-2.5-flash",
        contents= f"responda sucintamente: {pergunta}"
        )
    print(resposta)

    lista_de_respostas.append(resposta.text)
  return lista_de_respostas

In [ ]:
lista_respondida = responder_perguntas(lista_lida2)

#rodando a função

In [ ]:
lista_respondida

In [ ]:
# Etapa 4:

df = pd.DataFrame({
    "Pergunta": lista_lida2,
    "Resposta": lista_respondida
}) # df sugerido pela IA. Achei interessante testar o que fazia.

In [ ]:
df

In [ ]:
print(lista_lida2)
print(lista_respondida)

# as duas listas com suas respectivas respostas

In [ ]:
with open("resultados.csv", "w") as resultado:
  resultado.write("Pergunta,Resposta\n") # gerando cabeçalho

  for i in range(len(lista_lida2)): #gerando a lista de perguntas e respostas
    resultado.write(lista_lida2[i] + "," + lista_respondida[i] + "\n")

In [ ]:
# Etapa 5:

df = pd.read_csv("resultados.csv")

In [ ]:
df

In [ ]:
df.to_csv("resultados2.csv", index=False)

# Seguindo com Pandas

In [ ]:
import pandas as pd
import numpy as np
import random

# Definindo o número de linhas
num_linhas = 50

# --- Gerando Dados Fictícios ---

# 1. Nome do Produto (Nomes aleatórios simples)
nomes_base = ['Notebook', 'Mouse Sem Fio', 'Teclado Mecânico', 'Monitor UltraWide', 'Webcam HD', 'Fone de Ouvido Bluetooth', 'SSD 1TB', 'Roteador Wi-Fi 6', 'Placa de Vídeo RTX', 'Cadeira Gamer']
nomes_produtos = [f'{random.choice(nomes_base)} {i+1}' for i in range(num_linhas)]

# 2. Categoria do Produto (Escolha aleatória de categorias)
categorias = ['Eletrônicos', 'Periféricos', 'Hardware', 'Acessórios']
categoria_produto = np.random.choice(categorias, size=num_linhas)

# 3. Preço do Produto (Números decimais aleatórios)
# Gerando preços entre 50.00 e 5000.00
preco_produto = np.round(np.random.uniform(50.0, 5000.0, size=num_linhas), 2)

# 4. Quantos itens do produto foram vendidos (Números inteiros aleatórios)
# Gerando vendas entre 10 e 1000
itens_vendidos = np.random.randint(10, 1001, size=num_linhas)

# 5. Avaliação do Produto (Números decimais aleatórios para avaliação)
# Gerando avaliações entre 1.0 e 5.0
avaliacao_produto = np.round(np.random.uniform(1.0, 5.0, size=num_linhas), 1)

# --- Criando o Dicionário de Dados ---
dados = {
    'Nome do Produto': nomes_produtos,
    'Categoria do Produto': categoria_produto,
    'Preço do Produto': preco_produto,
    'Itens Vendidos': itens_vendidos,
    'Avaliação do Produto': avaliacao_produto
}

# --- Criando o DataFrame ---
df_produtos = pd.DataFrame(dados)

# --- Exibindo o DataFrame e sua estrutura ---
print(df_produtos.head())
print('\n--- Informações do DataFrame ---')
print(df_produtos.info())
print(f'\nO DataFrame possui {df_produtos.shape[0]} linhas e {df_produtos.shape[1]} colunas.')

              Nome do Produto Categoria do Produto  Preço do Produto  \
0                 Webcam HD 1           Acessórios           4073.97
1             Mouse Sem Fio 2          Eletrônicos           2445.56
2  Fone de Ouvido Bluetooth 3           Acessórios           2794.06
3          Roteador Wi-Fi 6 4          Periféricos           3537.03
4             Mouse Sem Fio 5             Hardware            155.19

   Itens Vendidos  Avaliação do Produto
0             188                   2.6
1             381                   3.1
2             391                   3.1
3             739                   2.0
4             126                   3.8

--- Informações do DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Nome do Produto       50 non-null     object
 1   Categoria do Produto  50 non-null     object
 2   Preço do Produto      50 non-null     float64
 3   Itens Vendidos        50 non-null     int64
 4   Avaliação do Produto  50 non-null     float64
dtypes: float64(2), int64(1), object(2)
memory usage: 2.1+ KB
None

O DataFrame possui 50 linhas e 5 colunas.

In [ ]:
df_produtos

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
0,Webcam HD 1,Acessórios,4073.97,188,2.6
1,Mouse Sem Fio 2,Eletrônicos,2445.56,381,3.1
2,Fone de Ouvido Bluetooth 3,Acessórios,2794.06,391,3.1
3,Roteador Wi-Fi 6 4,Periféricos,3537.03,739,2.0
4,Mouse Sem Fio 5,Hardware,155.19,126,3.8
5,Webcam HD 6,Periféricos,3682.24,530,1.3
6,Monitor UltraWide 7,Periféricos,2161.61,203,4.8
7,Notebook 8,Hardware,4264.40,268,2.7
8,Monitor UltraWide 9,Periféricos,3884.63,420,1.6
9,SSD 1TB 10,Eletrônicos,2767.97,936,4.9
10,Notebook 11,Periféricos,4608.86,350,4.4
11,Monitor UltraWide 12,Hardware,4001.89,869,4.3
12,Monitor UltraWide 13,Periféricos,2113.51,106,1.3
13,Monitor UltraWide 14,Eletrônicos,3603.58,890,3.4
14,Cadeira Gamer 15,Hardware,641.01,806,4.4
15,Placa de Vídeo RTX 16,Periféricos,1643.45,430,1.3
16,SSD 1TB 17,Acessórios,1293.26,635,3.1
17,Notebook 18,Acessórios,341.79,291,1.7
18,Fone de Ouvido Bluetooth 19,Acessórios,4445.17,476,1.3
19,Roteador Wi-Fi 6 20,Eletrônicos,368.27,651,1.5
20,SSD 1TB 21,Hardware,4074.72,968,3.3
21,Cadeira Gamer 22,Eletrônicos,1784.42,444,2.0
22,Mouse Sem Fio 23,Hardware,4938.69,433,3.8
23,Monitor UltraWide 24,Hardware,118.30,535,4.1
24,Notebook 25,Eletrônicos,1755.71,550,2.0
25,Roteador Wi-Fi 6 26,Eletrônicos,3988.58,771,3.6
26,Fone de Ouvido Bluetooth 27,Hardware,3667.37,575,1.0
27,Teclado Mecânico 28,Acessórios,2113.01,740,1.6
28,Webcam HD 29,Acessórios,2220.05,299,4.3
29,Cadeira Gamer 30,Eletrônicos,2205.98,549,1.5
30,Cadeira Gamer 31,Acessórios,4044.43,733,2.3
31,Monitor UltraWide 32,Hardware,1136.32,652,3.2
32,SSD 1TB 33,Periféricos,451.15,908,2.0
33,Mouse Sem Fio 34,Acessórios,173.76,144,3.1
34,Mouse Sem Fio 35,Periféricos,3853.30,695,3.0
35,Mouse Sem Fio 36,Eletrônicos,620.61,455,4.3
36,Cadeira Gamer 37,Acessórios,1457.30,174,3.7
37,Placa de Vídeo RTX 38,Eletrônicos,1426.29,99,1.0
38,Notebook 39,Acessórios,745.16,499,4.9
39,Webcam HD 40,Periféricos,2775.13,58,1.5
40,Teclado Mecânico 41,Hardware,2184.99,356,4.9
41,Fone de Ouvido Bluetooth 42,Eletrônicos,3018.16,85,3.6
42,SSD 1TB 43,Acessórios,3419.97,443,1.6
43,Placa de Vídeo RTX 44,Eletrônicos,2191.21,927,3.4
44,SSD 1TB 45,Eletrônicos,4586.07,810,3.8
45,Notebook 46,Hardware,4964.34,787,4.1
46,Roteador Wi-Fi 6 47,Acessórios,4563.72,782,4.1
47,Mouse Sem Fio 48,Eletrônicos,147.82,266,2.4
48,Mouse Sem Fio 49,Hardware,2119.67,654,3.0
49,Notebook 50,Periféricos,4700.47,10,1.1

In [ ]:
df_produtos["Categoria do Produto"].unique()

array(['Acessórios', 'Eletrônicos', 'Periféricos', 'Hardware'],
      dtype=object)

In [ ]:
set(df_produtos["Categoria do Produto"])

{'Acessórios', 'Eletrônicos', 'Hardware', 'Periféricos'}

In [ ]:
# Filtrar elementos do DataFrame

# Suponho que quero todos os produtos da categoria "eletrônicos"

df_produtos["Categoria do Produto"] == "Eletrônicos"

# Não vai dar certo, vai gerar um booleano com True e False considerando onde tem ou não eletrônicos

0     False
1      True
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13     True
14    False
15    False
16    False
17    False
18    False
19     True
20    False
21     True
22    False
23    False
24     True
25     True
26    False
27    False
28    False
29     True
30    False
31    False
32    False
33    False
34    False
35     True
36    False
37     True
38    False
39    False
40    False
41     True
42    False
43     True
44     True
45    False
46    False
47     True
48    False
49    False
Name: Categoria do Produto, dtype: bool

In [ ]:
df_produtos[df_produtos["Categoria do Produto"] == "Eletrônicos"]

# no formato df_produtos[i] onde i é a condição, a saber, onde "Categoria do
# Produto] é igual a Eletrônicos

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
1,Mouse Sem Fio 2,Eletrônicos,2445.56,381,3.1
9,SSD 1TB 10,Eletrônicos,2767.97,936,4.9
13,Monitor UltraWide 14,Eletrônicos,3603.58,890,3.4
19,Roteador Wi-Fi 6 20,Eletrônicos,368.27,651,1.5
21,Cadeira Gamer 22,Eletrônicos,1784.42,444,2.0
24,Notebook 25,Eletrônicos,1755.71,550,2.0
25,Roteador Wi-Fi 6 26,Eletrônicos,3988.58,771,3.6
29,Cadeira Gamer 30,Eletrônicos,2205.98,549,1.5
35,Mouse Sem Fio 36,Eletrônicos,620.61,455,4.3
37,Placa de Vídeo RTX 38,Eletrônicos,1426.29,99,1.0
41,Fone de Ouvido Bluetooth 42,Eletrônicos,3018.16,85,3.6
43,Placa de Vídeo RTX 44,Eletrônicos,2191.21,927,3.4
44,SSD 1TB 45,Eletrônicos,4586.07,810,3.8
47,Mouse Sem Fio 48,Eletrônicos,147.82,266,2.4

In [ ]:
i = df_produtos["Avaliação do Produto"] < 2
df_produtos[i]

# outro exemplo. Percebe que dá certo declarando i e depois usando na lista
# teoricamente, deveria usar 2.0. Usei 2 inteiro pra testar

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
5,Webcam HD 6,Periféricos,3682.24,530,1.3
8,Monitor UltraWide 9,Periféricos,3884.63,420,1.6
12,Monitor UltraWide 13,Periféricos,2113.51,106,1.3
15,Placa de Vídeo RTX 16,Periféricos,1643.45,430,1.3
17,Notebook 18,Acessórios,341.79,291,1.7
18,Fone de Ouvido Bluetooth 19,Acessórios,4445.17,476,1.3
19,Roteador Wi-Fi 6 20,Eletrônicos,368.27,651,1.5
26,Fone de Ouvido Bluetooth 27,Hardware,3667.37,575,1.0
27,Teclado Mecânico 28,Acessórios,2113.01,740,1.6
29,Cadeira Gamer 30,Eletrônicos,2205.98,549,1.5
37,Placa de Vídeo RTX 38,Eletrônicos,1426.29,99,1.0
39,Webcam HD 40,Periféricos,2775.13,58,1.5
42,SSD 1TB 43,Acessórios,3419.97,443,1.6
49,Notebook 50,Periféricos,4700.47,10,1.1

In [ ]:
df_produtos.shape

# mostra linhas e colunas. Shape não é método pq não tem (), portanto é um atributo

(50, 5)

In [ ]:
# para filtrar e descobrir quantas linhas tem numa condição:

valor_menor_que_mil = df_produtos[df_produtos["Preço do Produto"] < 1000.00]
valor_menor_que_mil.shape

# resultado: tem cinco elementos com valor menor que mil

(10, 5)

In [ ]:
# usando mais de uma condição:

df_produtos[(df_produtos["Categoria do Produto"] == "Eletrônicos") & (df_produtos["Avaliação do Produto"] >= 2.0) ]

# usa o & e tem que botar as condições entre parênteses

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
1,Mouse Sem Fio 2,Eletrônicos,2445.56,381,3.1
9,SSD 1TB 10,Eletrônicos,2767.97,936,4.9
13,Monitor UltraWide 14,Eletrônicos,3603.58,890,3.4
21,Cadeira Gamer 22,Eletrônicos,1784.42,444,2.0
24,Notebook 25,Eletrônicos,1755.71,550,2.0
25,Roteador Wi-Fi 6 26,Eletrônicos,3988.58,771,3.6
35,Mouse Sem Fio 36,Eletrônicos,620.61,455,4.3
41,Fone de Ouvido Bluetooth 42,Eletrônicos,3018.16,85,3.6
43,Placa de Vídeo RTX 44,Eletrônicos,2191.21,927,3.4
44,SSD 1TB 45,Eletrônicos,4586.07,810,3.8
47,Mouse Sem Fio 48,Eletrônicos,147.82,266,2.4

In [ ]:
df_produtos.iloc[15]

#localiza o item de índice 15 no meu dataframe

Nome do Produto         Placa de Vídeo RTX 16
Categoria do Produto              Periféricos
Preço do Produto                      1643.45
Itens Vendidos                            430
Avaliação do Produto                      1.3
Name: 15, dtype: object

In [ ]:
df_produtos.iloc[0:16]

# dá pra fazer tudo que se faz com uma lista, como mostrar do 0 ao 16

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
0,Webcam HD 1,Acessórios,4073.97,188,2.6
1,Mouse Sem Fio 2,Eletrônicos,2445.56,381,3.1
2,Fone de Ouvido Bluetooth 3,Acessórios,2794.06,391,3.1
3,Roteador Wi-Fi 6 4,Periféricos,3537.03,739,2.0
4,Mouse Sem Fio 5,Hardware,155.19,126,3.8
5,Webcam HD 6,Periféricos,3682.24,530,1.3
6,Monitor UltraWide 7,Periféricos,2161.61,203,4.8
7,Notebook 8,Hardware,4264.40,268,2.7
8,Monitor UltraWide 9,Periféricos,3884.63,420,1.6
9,SSD 1TB 10,Eletrônicos,2767.97,936,4.9
10,Notebook 11,Periféricos,4608.86,350,4.4
11,Monitor UltraWide 12,Hardware,4001.89,869,4.3
12,Monitor UltraWide 13,Periféricos,2113.51,106,1.3
13,Monitor UltraWide 14,Eletrônicos,3603.58,890,3.4
14,Cadeira Gamer 15,Hardware,641.01,806,4.4
15,Placa de Vídeo RTX 16,Periféricos,1643.45,430,1.3

In [ ]:
df_produtos.iloc[34:42]

#mostra do 34 ao 42

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
34,Mouse Sem Fio 35,Periféricos,3853.30,695,3.0
35,Mouse Sem Fio 36,Eletrônicos,620.61,455,4.3
36,Cadeira Gamer 37,Acessórios,1457.30,174,3.7
37,Placa de Vídeo RTX 38,Eletrônicos,1426.29,99,1.0
38,Notebook 39,Acessórios,745.16,499,4.9
39,Webcam HD 40,Periféricos,2775.13,58,1.5
40,Teclado Mecânico 41,Hardware,2184.99,356,4.9
41,Fone de Ouvido Bluetooth 42,Eletrônicos,3018.16,85,3.6

In [ ]:
df_produtos.iloc[43:]

# mostra do 43 ao final

,Nome do Produto,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
43,Placa de Vídeo RTX 44,Eletrônicos,2191.21,927,3.4
44,SSD 1TB 45,Eletrônicos,4586.07,810,3.8
45,Notebook 46,Hardware,4964.34,787,4.1
46,Roteador Wi-Fi 6 47,Acessórios,4563.72,782,4.1
47,Mouse Sem Fio 48,Eletrônicos,147.82,266,2.4
48,Mouse Sem Fio 49,Hardware,2119.67,654,3.0
49,Notebook 50,Periféricos,4700.47,10,1.1

In [ ]:
df_produtos_com_indice = df_produtos.set_index("Nome do Produto")
df_produtos_com_indice

,Categoria do Produto,Preço do Produto,Itens Vendidos,Avaliação do Produto
Nome do Produto,,,,
Webcam HD 1,Acessórios,4073.97,188,2.6
Mouse Sem Fio 2,Eletrônicos,2445.56,381,3.1
Fone de Ouvido Bluetooth 3,Acessórios,2794.06,391,3.1
Roteador Wi-Fi 6 4,Periféricos,3537.03,739,2.0
Mouse Sem Fio 5,Hardware,155.19,126,3.8
Webcam HD 6,Periféricos,3682.24,530,1.3
Monitor UltraWide 7,Periféricos,2161.61,203,4.8
Notebook 8,Hardware,4264.40,268,2.7
Monitor UltraWide 9,Periféricos,3884.63,420,1.6
SSD 1TB 10,Eletrônicos,2767.97,936,4.9
Notebook 11,Periféricos,4608.86,350,4.4
Monitor UltraWide 12,Hardware,4001.89,869,4.3
Monitor UltraWide 13,Periféricos,2113.51,106,1.3
Monitor UltraWide 14,Eletrônicos,3603.58,890,3.4
Cadeira Gamer 15,Hardware,641.01,806,4.4
Placa de Vídeo RTX 16,Periféricos,1643.45,430,1.3
SSD 1TB 17,Acessórios,1293.26,635,3.1
Notebook 18,Acessórios,341.79,291,1.7
Fone de Ouvido Bluetooth 19,Acessórios,4445.17,476,1.3
Roteador Wi-Fi 6 20,Eletrônicos,368.27,651,1.5
SSD 1TB 21,Hardware,4074.72,968,3.3
Cadeira Gamer 22,Eletrônicos,1784.42,444,2.0
Mouse Sem Fio 23,Hardware,4938.69,433,3.8
Monitor UltraWide 24,Hardware,118.30,535,4.1
Notebook 25,Eletrônicos,1755.71,550,2.0
Roteador Wi-Fi 6 26,Eletrônicos,3988.58,771,3.6
Fone de Ouvido Bluetooth 27,Hardware,3667.37,575,1.0
Teclado Mecânico 28,Acessórios,2113.01,740,1.6
Webcam HD 29,Acessórios,2220.05,299,4.3
Cadeira Gamer 30,Eletrônicos,2205.98,549,1.5
Cadeira Gamer 31,Acessórios,4044.43,733,2.3
Monitor UltraWide 32,Hardware,1136.32,652,3.2
SSD 1TB 33,Periféricos,451.15,908,2.0
Mouse Sem Fio 34,Acessórios,173.76,144,3.1
Mouse Sem Fio 35,Periféricos,3853.30,695,3.0
Mouse Sem Fio 36,Eletrônicos,620.61,455,4.3
Cadeira Gamer 37,Acessórios,1457.30,174,3.7
Placa de Vídeo RTX 38,Eletrônicos,1426.29,99,1.0
Notebook 39,Acessórios,745.16,499,4.9
Webcam HD 40,Periféricos,2775.13,58,1.5
Teclado Mecânico 41,Hardware,2184.99,356,4.9
Fone de Ouvido Bluetooth 42,Eletrônicos,3018.16,85,3.6
SSD 1TB 43,Acessórios,3419.97,443,1.6
Placa de Vídeo RTX 44,Eletrônicos,2191.21,927,3.4
SSD 1TB 45,Eletrônicos,4586.07,810,3.8
Notebook 46,Hardware,4964.34,787,4.1
Roteador Wi-Fi 6 47,Acessórios,4563.72,782,4.1
Mouse Sem Fio 48,Eletrônicos,147.82,266,2.4
Mouse Sem Fio 49,Hardware,2119.67,654,3.0
Notebook 50,Periféricos,4700.47,10,1.1

In [ ]:
df_produtos_com_indice.loc["Roteador Wi-Fi 6 15"]

# "loc" funciona igual iloc, mas o índice é o nome de cada item

KeyError: 'Roteador Wi-Fi 6 15'

In [ ]:
df_produtos_com_indice.loc[:"Teclado Mecânico 6"]

#mostra do primeiro até o produto mencionado

KeyError: 'Teclado Mecânico 6'

In [ ]:
# quero localizar um produto e mostrar apenas a coluna do preço

df_produtos_com_indice.loc["Teclado Mecânico 6", "Preço do Produto"]

#mostrou apenas o float referente ao preço.

In [ ]:
#se eu fizer com ":", ele vai mostrar uma lista do zero ao item mencionado, só com a coluna informada

df_produtos_com_indice.loc[:"Teclado Mecânico 6", "Preço do Produto"]

In [ ]:
df_produtos_com_indice.loc["Monitor UltraWide 3":"Teclado Mecânico 6", ["Preço do Produto", "Itens Vendidos"]]

# atentar para colchetes. eu posso usar "Monitor UltraWide 3":"Teclado Mecânico 6" sem colchetes, ou usar colchetes e passar uma lista de elementos.
# mas depois da vírgula eu PRECISO usar colchetes para informar as colunas que eu quero

In [ ]:
eletronicos = df_produtos_com_indice[df_produtos_com_indice["Categoria do Produto"] == "Eletrônicos"]
# Salvei a tabela que é só dos eletrônicos

df_produtos_com_indice.loc[eletronicos.index, ["Preço do Produto", "Itens Vendidos"]]

#no caso, eletronicos.index é a lista de elementos, equivalente na célula anterior ao "Monitor UltraWide 3":"Teclado Mecânico 6".

In [ ]:
#agora pretendo trocar o nome "Eletrônicos" por "Prod. Eletr."

eletronicos = df_produtos_com_indice[df_produtos_com_indice["Categoria do Produto"] == "Eletrônicos"]
#declarando de novo, apenas para ficar tudo na mesma célula

df_produtos_com_indice.loc[eletronicos.index, "Categoria do Produto"]
# se eu uso só essa linha ele me mostra todos os eletrônicos, então se eu der '=' eu consigo atribuir um outro valor na coluna

df_produtos_com_indice.loc[eletronicos.index, "Categoria do Produto"] = "Prod. Eletr."

In [ ]:
df_produtos_com_indice.loc[eletronicos.index, "Categoria do Produto"]

#agora já está alterado. Se der um 'unique' já aparece a nova Categoria

In [ ]:
df_produtos_com_indice["Categoria do Produto"].unique()

## exercício da aula

In [ ]:
# Desafio: 1.Carregar um arquivo .csv com feedback de clientes,
# 2. usar um LLM para classificar o sentimento de cada feedback (positivo, negativo, neutro)
# 3. e adicionar uma nova coluna com essa classificação ao DataFrame.

# Etapa 1:

df_reviews = pd.read_csv("reviews.csv")

In [ ]:
df_reviews.head()

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0

In [ ]:
# @title
# Etapa 2:

import os
from google.colab import userdata
os.environ["GOOGLE_API_KEY"] = userdata.get('chave_teste')

from google import genai
minha_IA = genai.Client()

def classificar_sentimento(review):
  lista_de_sentimentos = []
  for i, review in enumerate(review):
    sentimento = minha_IA.models.generate_content(
        model = "gemini-2.5-flash",
        contents = f"vou te fornecer um review de um produto, e peço que APENAS classifique o seguinte review como 'Positivo', 'Negativo' ou 'Neutro' (não explique nada, somente use uma das palavras mencionadas): {review}"
    )
    print(sentimento.text)
    lista_de_sentimentos.append(sentimento.text)
  return lista_de_sentimentos
# definida a função, basta rodar com a coluna "reviewText"

df_reviews["reviewText"]

0     it works as expected. I should have sprung for...
1     This think has worked out great.Had a diff. br...
2     Bought it with Retail Packaging, arrived legit...
3     It's mini storage.  It doesn't do anything els...
4     I have it in my phone and it never skips a bea...
5     It works, but file writes are a bit slower tha...
6     I bought 2 of those SanDisk 32 GB microSD , us...
7     The memory card is an excellent condition and ...
8     I bougth this micro SD card after some trubles...
9     Ordered this for a Galaxy S3.  Lasted a few mo...
10    more like 8mb/s in my Note 10.1 and that's usi...
11    I used this for a few months in my phone, then...
12    everything about it was great, except for the ...
13    Used in my phone it's plenty fast and works ju...
14    This card advertises itself as UHS1 but it's a...
15    I bought this SD card for my android phone thi...
16    good card. work as describes. haven't had any ...
17    I got this because I just couldn't pass up the...
18    It works but the actual R/W speeds are 18/8 MB...
19    Does it's job and fairly cheap for what it's w...
20    Still don't feel is very fast or is just my ph...
21    I bought 64GB version of the card to use with ...
22    I have an old SanDisk SD card that still works...
23    Used it in my Galaxy Note 2 for the past 16 mo...
24    Worked great in my galaxy s4--until it didn't ...
25    I bought this on August of 2013.  As of April ...
26    So this product is a large disappointment...bo...
27    I will keep it short and sweet for potential b...
28    The package arrived on time, it's very well pa...
29    Does what it says. Hasn't broken yet, and I ho...
30    Thus microSD card worked fine for a year in my...
31    I think this is probably a fine product, but i...
32    I have two of these and use them for my Galazy...
33    I join the long list of customers who have had...
34    I do not get the advertised speed of 30MB/s, m...
35    the micro sd works great as described. but bew...
36    than i expected. I don't know if it would kill...
37    Reliable and inexpensive. However, it's quite ...
38    I bought this primarily to use in my Surface P...
39    I really don't know what to think about this I...
Name: reviewText, dtype: object

In [ ]:
df_reviews["reviewText"][0:5]

0    it works as expected. I should have sprung for...
1    This think has worked out great.Had a diff. br...
2    Bought it with Retail Packaging, arrived legit...
3    It's mini storage.  It doesn't do anything els...
4    I have it in my phone and it never skips a bea...
Name: reviewText, dtype: object

In [ ]:
lista_de_sentimentos = classificar_sentimento(df_reviews["reviewText"][0:5])

Negativo
Positivo
Positivo
Positivo
Positivo

In [ ]:
import random

for i in range(35):
  lista_de_sentimentos.append(random.choice(["Positivo", "Neutro", "Negativo"]))

print(lista_de_sentimentos)

['Negativo', 'Positivo', 'Positivo', 'Positivo', 'Positivo', 'Negativo', 'Positivo', 'Negativo', 'Negativo', 'Neutro', 'Positivo', 'Neutro', 'Negativo', 'Negativo', 'Positivo', 'Neutro', 'Positivo', 'Negativo', 'Negativo', 'Neutro', 'Neutro', 'Neutro', 'Positivo', 'Negativo', 'Negativo', 'Neutro', 'Neutro', 'Neutro', 'Positivo', 'Neutro', 'Neutro', 'Negativo', 'Negativo', 'Negativo', 'Negativo', 'Neutro', 'Positivo', 'Neutro', 'Negativo', 'Negativo']

In [ ]:
lista_de_sentimentos

['Negativo',
 'Positivo',
 'Positivo',
 'Positivo',
 'Positivo',
 'Negativo',
 'Positivo',
 'Negativo',
 'Negativo',
 'Neutro',
 'Positivo',
 'Neutro',
 'Negativo',
 'Negativo',
 'Positivo',
 'Neutro',
 'Positivo',
 'Negativo',
 'Negativo',
 'Neutro',
 'Neutro',
 'Neutro',
 'Positivo',
 'Negativo',
 'Negativo',
 'Neutro',
 'Neutro',
 'Neutro',
 'Positivo',
 'Neutro',
 'Neutro',
 'Negativo',
 'Negativo',
 'Negativo',
 'Negativo',
 'Neutro',
 'Positivo',
 'Neutro',
 'Negativo',
 'Negativo']

In [ ]:
# Etapa 3:

# Adicionar a lista_de_sentimentos existente como uma nova coluna 'sentimento' ao DataFrame
df_reviews['Coluna de Sentimentos'] = lista_de_sentimentos

# Exibir as primeiras linhas do DataFrame com a nova coluna
display(df_reviews)

# Não vi diferença entre o método display e simplesmente digitar "df_reviews"

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Coluna de Sentimentos
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Negativo
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positivo
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positivo
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positivo
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positivo
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0,Negativo
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Positivo
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0,Negativo
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativo
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Neutro
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,Positivo
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Neutro
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,Negativo
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0,Negativo
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,Positivo
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0,Neutro
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0,Positivo
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,Negativo
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0,Negativo
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0,Neutro
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0,Neutro
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1,Neutro
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0,Positivo
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0,Negativo
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0,Negativo
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1,Neutro
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0,Neutro
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0,Neutro
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0,Positivo
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1,Neutro
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3,Neutro
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1,Negativo
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,Negativo
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2,Negativo
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1,Negativo
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0,Neutro
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2,Positivo
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0,Neutro
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0,Negativo
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0,Negativo

In [ ]:
df_reviews

,reviewerID,asin,reviewerName,reviewText,unixReviewTime,reviewTime,day_diff,helpful_yes,total_vote,Coluna de Sentimentos
0,A2FII3I2MBMUIA,B007WTAJTO,1K3,it works as expected. I should have sprung for...,1356220800,23/12/2012,715,0,0,Negativo
1,A3H99DFEG68SR,B007WTAJTO,1m2,This think has worked out great.Had a diff. br...,1384992000,21/11/2013,382,0,0,Positivo
2,A375ZM4U047O79,B007WTAJTO,2&amp;1/2Men,"Bought it with Retail Packaging, arrived legit...",1373673600,13/07/2013,513,0,0,Positivo
3,A2IDCSC6NVONIZ,B007WTAJTO,2Cents!,It's mini storage. It doesn't do anything els...,1367193600,29/04/2013,588,0,0,Positivo
4,A26YHXZD5UFPVQ,B007WTAJTO,2K1Toaster,I have it in my phone and it never skips a bea...,1382140800,19/10/2013,415,0,0,Positivo
5,A2Q3ICGWZLY3JJ,B007WTAJTO,98020,"It works, but file writes are a bit slower tha...",1384905600,20/11/2013,383,0,0,Negativo
6,AF24M1HKIZ7QC,B007WTAJTO,"Abdulrahman J. Alrashed ""dr34m3r""","I bought 2 of those SanDisk 32 GB microSD , us...",1375488000,08/03/2013,640,0,0,Positivo
7,A1KIF9Z5VFPH7H,B007WTAJTO,"Abel Feliciano ""Ace Master""",The memory card is an excellent condition and ...,1347321600,09/11/2012,759,0,0,Negativo
8,A1FKE13D77L3Y3,B007WTAJTO,Abraham Arturo Meza Marin,I bougth this micro SD card after some trubles...,1361232000,19/02/2013,657,0,0,Negativo
9,A1X1FX3NSOFCT3,B007WTAJTO,"Abused Commuter ""abused_commuter""",Ordered this for a Galaxy S3. Lasted a few mo...,1374278400,20/07/2013,506,0,1,Neutro
10,A3RV1L35IPTV61,B007WTAJTO,abushaheed,more like 8mb/s in my Note 10.1 and that's usi...,1357430400,01/06/2013,555,0,0,Positivo
11,A2RJ7DAL63MN1F,B007WTAJTO,Ace of Sevens,"I used this for a few months in my phone, then...",1391126400,31/01/2014,311,0,0,Neutro
12,A3IJIFZ5HH819V,B007WTAJTO,A. Cho,"everything about it was great, except for the ...",1373414400,07/10/2013,427,0,0,Negativo
13,A1R0JMNRV7HVQM,B007WTAJTO,ACZ,Used in my phone it's plenty fast and works ju...,1383609600,11/05/2013,576,0,0,Negativo
14,APAEBFIM1588A,B007WTAJTO,"Adam Wright ""Electrical Engineer""",This card advertises itself as UHS1 but it's a...,1378684800,09/09/2013,455,1,1,Positivo
15,A1JOXGZH55JMHW,B007WTAJTO,A. Hejazi,I bought this SD card for my android phone thi...,1386806400,12/12/2013,361,0,0,Neutro
16,A35NR2GQWMQ31K,B007WTAJTO,ahhsimon,good card. work as describes. haven't had any ...,1391644800,02/06/2014,189,0,0,Positivo
17,A1N7LGUPJWWQS9,B007WTAJTO,A.J. Matheson,I got this because I just couldn't pass up the...,1353888000,26/11/2012,742,0,0,Negativo
18,A28CTDM7OP0RAR,B007WTAJTO,Alan,It works but the actual R/W speeds are 18/8 MB...,1395705600,25/03/2014,258,0,0,Negativo
19,A1NA2JGI3GNDN2,B007WTAJTO,Albert,Does it's job and fairly cheap for what it's w...,1399161600,05/04/2014,247,0,0,Neutro
20,A3PCW69GQK8R38,B007WTAJTO,Alejandro Hernndez,Still don't feel is very fast or is just my ph...,1391385600,02/03/2014,281,0,0,Neutro
21,A1UM44ILLZCEI1,B007WTAJTO,Aleksandar Milivojevic,I bought 64GB version of the card to use with ...,1364947200,04/03/2013,644,1,1,Neutro
22,A2T71JNR3C2DY1,B007WTAJTO,"Ali Etezadkhah ""Ali""",I have an old SanDisk SD card that still works...,1371859200,22/06/2013,534,0,0,Positivo
23,A87U7LY9OKZNY,B007WTAJTO,A. Liu,Used it in my Galaxy Note 2 for the past 16 mo...,1398988800,05/02/2014,306,0,0,Negativo
24,A277QWS5WF6DWI,B007WTAJTO,Alton L Spencer,Worked great in my galaxy s4--until it didn't ...,1401148800,27/05/2014,195,0,0,Negativo
25,A1WWPAQ1DD6BQC,B007WTAJTO,A. Marte,I bought this on August of 2013. As of April ...,1403654400,25/06/2014,166,1,1,Neutro
26,A3FY6V3LXP8SSL,B007WTAJTO,"Amazon Customer ""fiction buff""",So this product is a large disappointment...bo...,1349136000,10/02/2012,1032,0,0,Neutro
27,A3DXCQV1U6QLTS,B007WTAJTO,Amazon Customer,I will keep it short and sweet for potential b...,1360195200,02/07/2013,524,0,0,Neutro
28,A3R2TY7PFN9VSM,B007WTAJTO,Amazon Customer,"The package arrived on time, it's very well pa...",1375660800,08/05/2013,579,0,0,Positivo
29,A1FZKP9XTKMALD,B007WTAJTO,Amazon Customer,"Does what it says. Hasn't broken yet, and I ho...",1375401600,08/02/2013,668,0,1,Neutro
30,A308JP3BK4VAL7,B007WTAJTO,Amazon Customer,Thus microSD card worked fine for a year in my...,1398643200,28/04/2014,224,0,3,Neutro
31,A392ZR68AKLDCK,B007WTAJTO,"Amazon Customer ""Music Fan""","I think this is probably a fine product, but i...",1374796800,26/07/2013,500,1,1,Negativo
32,A2DQ2U5BYIXNUJ,B007WTAJTO,"Amazon Customer ""PawsitivelySafe""",I have two of these and use them for my Galazy...,1387152000,16/12/2013,357,0,0,Negativo
33,A14D2PS27PI3FM,B007WTAJTO,Amazon Fan,I join the long list of customers who have had...,1359936000,02/04/2013,615,1,2,Negativo
34,A1Z7FZP81N8CDU,B007WTAJTO,Amazon Shopper,"I do not get the advertised speed of 30MB/s, m...",1394755200,14/03/2014,269,0,1,Negativo
35,A1T8FVB93QQNOM,B007WTAJTO,Andrew M. Swiatek,the micro sd works great as described. but bew...,1372464000,29/06/2013,527,0,0,Neutro
36,A3K1JZPUXSADRJ,B007WTAJTO,anonomous,than i expected. I don't know if it would kill...,1362182400,03/02/2013,673,0,2,Positivo
37,A1D07XDTMWV0A5,B007WTAJTO,"A. Shieh ""eff.org""","Reliable and inexpensive. However, it's quite ...",1385769600,30/11/2013,373,0,0,Neutro
38,A1HKW2TELCHGLL,B007WTAJTO,astraelraen,I bought this primarily to use in my Surface P...,1391040000,30/01/2014,312,0,0,Negativo
39,A3P86Z2D81VLYV,B007WTAJTO,"Zeality ""N2iT""",I really don't know what to think about this I...,1396137600,30/03/2014,253,0,0,Negativo

# Exceções -> try/except/finally

In [ ]:
# imagina que vamos tentar fazer algo errado, como converter para inteiro uma string "abc"

int("abc")

# sabemos que vai dar erro, nesse caso um "ValueError"

ValueError: invalid literal for int() with base 10: 'abc'

In [ ]:
# do mesmo jeito, no código abaixo, se eu digitar em vez de um número uma string, vai dar um "ValueError"

pegando_algo = int(input("Digite a sua idade: "))

Digite a sua idade: abc

ValueError: invalid literal for int() with base 10: 'abc'

In [5]:
# existem vários outros tipos de erros. Por exemplo, se eu tentar somar string com ints

pessoas = 6
pessoas2 = "Mario, Joao, Silvia, Maria"

pessoas + pessoas2

# esse código vai dar um TypeError, um erro de tipo de variável

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [8]:
# Para continuar o programa sem crashar existem recursos para tratar esses erros
# Por exemplo, no exemplo de pegando algo (ValueError):

try:
  pegando_algo = int(input("Digite a sua idade: "))
except:
  print("Você não digitou um número inteiro válido")

# inclusive é possível (e recomendável) criar as minhas próprias exceções

Digite a sua idade: 12.1
Você não digitou um número inteiro válido

In [10]:
# note que no exemplo acima eu não especifiquei o erro que era pra dar.
# Mais corretamente, meu código deveria enunciar exatamente o erro esperado

try:
  pegando_algo = int(input("Digite a sua idade: "))
  pessoas = 6
  pessoas2 = "Mario, Joao, Silvia, Maria"

  pessoas + pessoas2

except ValueError:
  print("Você não digitou um número inteiro válido")
except TypeError:
  print("Você não pode somar strings com ints")

# Nesse exemplo sempre vai dar TypeError, porque o erro está "no código" (e não no input). Só foi usado pra demonstrar como se encadeia exceções.

Digite a sua idade: 12
Você não pode somar strings com ints

In [13]:
# é possível dar "apelidos" aos erros usando "as"

try:
  pegando_algo = int(input("Digite a sua idade: "))
  pessoas = 6
  pessoas2 = "Mario, Joao, Silvia, Maria"

  pessoas + pessoas2

except ValueError as ve:  # ve como apelido de ValueError
  print("Você não digitou um número inteiro válido")
  print("Detalhes do erro:", ve) #ve se torna o texto do erro
except TypeError:
  print("Você não pode somar strings com ints")

Digite a sua idade: qwe
Você não digitou um número inteiro válido
Detalhes do erro: invalid literal for int() with base 10: 'qwe'

In [14]:
try:
  pegando_algo = int(input("Digite a sua idade: "))
  pessoas = 6
  pessoas2 = "Mario, Joao, Silvia, Maria"

  pessoas + pessoas2

except ValueError:  # teste para verificar se é possível expôr o texto do erro sem usar "as"
  print("Você não digitou um número inteiro válido")
  print("Detalhes do erro:", ValueError) #retorna o texto do erro
except TypeError:
  print("Você não pode somar strings com ints")

  ###################### não dá certo. TEM QUE USAR AS !!!!!!

Digite a sua idade: qwe
Você não digitou um número inteiro válido
Detalhes do erro: <class 'ValueError'>

In [16]:
try:
  pegando_algo = int(input("Digite a sua idade: "))
  magica = 25/pegando_algo

  print(magica)

except ValueError as ve:
  print("Você não digitou um número inteiro válido")
  print("Detalhes do erro:", ve)
except TypeError:
  print("Você não pode somar strings com ints")

  # Nesse exemplo, existem exceções para ValueError e para TypeError, mas o código caiu num terceiro tipo de erro "não pensado"
  # para esses casos, é recomendado encontrar "Exception", que "pega todos os erros", caso não tenha caído em nenhum dos pensados

Digite a sua idade: 0

ZeroDivisionError: division by zero

In [17]:
try:
  pegando_algo = int(input("Digite a sua idade: "))
  magica = 25/pegando_algo

  print(magica)

except ValueError as ve:
  print("Você não digitou um número inteiro válido")
  print("Detalhes do erro:", ve)
except TypeError:
  print("Você não pode somar strings com ints")
except Exception as e: #Permite que o código não crashe, importante!
  print("DEU RUIM GERAL")
  print("Detalhes do erro:",e)

Digite a sua idade: 0
DEU RUIM GERAL
Detalhes do erro: division by zero

In [19]:
# por fim, existe o finally, para fazer alguma coisa INDEPENDENTEMENTE de onde deu erro. (pra não perder o progresso no meio de um programa)
# finally roda SE DER ERRO OU NÃO

try:
  pegando_algo = int(input("Digite a sua idade: "))
  magica = 25/pegando_algo

  print(magica)

except ValueError as ve:
  print("Você não digitou um número inteiro válido")
  print("Detalhes do erro:", ve)
except TypeError:
  print("Você não pode somar strings com ints")
except Exception as e:
  print("DEU RUIM GERAL")
  print("Detalhes do erro:",e)
finally:          # é opcional. Geralmente tem try e except, mas finally só às vezes.
  print("Finalizei o processo")

Digite a sua idade: 0
DEU RUIM GERAL
Detalhes do erro: division by zero
Finalizei o processo